In [19]:
from google.colab import files

uploaded = files.upload()

Saving Resume_data.zip to Resume_data.zip

In [20]:
print(uploaded.keys())

dict_keys(['Resume_data.zip'])

In [21]:
import zipfile
import os

zip_path = "Resume_data.zip"
extract_dir = "resumes_pdf"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_dir)

data_dir = os.path.join(extract_dir, "data")

print("Number of categories:", len(os.listdir(data_dir)))
print(os.listdir(data_dir))

Number of categories: 24
['DIGITAL-MEDIA', 'AVIATION', 'SALES', 'ADVOCATE', 'ARTS', 'ACCOUNTANT', 'TEACHER', 'HEALTHCARE', 'ENGINEERING', 'BPO', 'BANKING', 'APPAREL', 'PUBLIC-RELATIONS', 'CONSULTANT', 'FITNESS', 'INFORMATION-TECHNOLOGY', 'DESIGNER', 'FINANCE', 'CHEF', 'AGRICULTURE', 'AUTOMOBILE', 'BUSINESS-DEVELOPMENT', 'CONSTRUCTION', 'HR']

In [22]:
!pip install -q pymupdf

In [23]:
import pymupdf
import pandas as pd

In [26]:
extracted_resumes = []

for folder in os.listdir(data_dir):

    folder_path = os.path.join(data_dir, folder)

    if not os.path.isdir(folder_path):
        continue

    for file in os.listdir(folder_path):

        if not file.lower().endswith(".pdf"):
            continue

        file_path = os.path.join(folder_path, file)

        try:
            doc = pymupdf.open(file_path)

            text = ""

            for page in doc:
                text += page.get_text()

            doc.close()

            extracted_resumes.append({
                "filename": file,
                "label": folder,
                "text": text
            })

        except Exception as e:
            print(f"Error reading {file_path}: {e}")

In [27]:
df = pd.DataFrame(extracted_resumes)

print("Total resumes:", len(df))
print("Shape:", df.shape)

df.head()

Total resumes: 2484
Shape: (2484, 3)

,filename,label,text
0,24953921.pdf,DIGITAL-MEDIA,MEDIA SERVICES COORDINATOR\nSummary\nLife-long...
1,13837784.pdf,DIGITAL-MEDIA,DIGITAL MEDIA BUYER\nProfessional Summary\nVer...
2,18354623.pdf,DIGITAL-MEDIA,DIGITAL MARKETING MANAGER\nCareer Focus\nDigit...
3,40311088.pdf,DIGITAL-MEDIA,MEDIA SPECIALIST II\nProfessional Summary\nI w...
4,16893572.pdf,DIGITAL-MEDIA,DIGITAL MARKETING MANAGER\nSummary\nCreative m...

In [28]:
df["text"] = df["text"].fillna("").str.strip()

df = df[df["text"] != ""].reset_index(drop=True)

print("Usable resumes:", len(df))

Usable resumes: 2483

In [29]:
!pip install -q sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 34.2 MB/s eta 0:00:00

In [30]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

In [31]:
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Model loaded!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model loaded!

In [32]:
sample_embedding = embedding_model.encode(
    df.loc[0, "text"],
    convert_to_numpy=True
)

print(sample_embedding.shape)

(384,)

In [33]:
resume_embeddings = embedding_model.encode(
    df["text"].tolist(),
    convert_to_numpy=True,
    show_progress_bar=True,
    batch_size=32
)

print(resume_embeddings.shape)

Batches:   0%|          | 0/78 [00:00<?, ?it/s]

(2483, 384)

In [34]:
resume_embeddings = resume_embeddings.astype("float32")

faiss.normalize_L2(resume_embeddings)

In [35]:
embedding_dimension = resume_embeddings.shape[1]

index = faiss.IndexFlatIP(
    embedding_dimension
)

index.add(resume_embeddings)

print("Number of resumes in index:", index.ntotal)

Number of resumes in index: 2483

In [36]:
def search_resumes(query, top_k=5):

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True
    ).astype("float32")

    faiss.normalize_L2(query_embedding)

    scores, indices = index.search(
        query_embedding,
        top_k
    )

    results = df.iloc[indices[0]].copy()

    results["similarity_score"] = scores[0]

    return results[
        [
            "filename",
            "label",
            "similarity_score",
            "text"
        ]
    ]

In [37]:
query = """
Candidate with experience in Python, machine learning,
data analysis and predictive modeling.
"""

results = search_resumes(query, top_k=5)

results[
    ["filename", "label", "similarity_score"]
]

          filename                   label  similarity_score
2121  18448085.pdf              AUTOMOBILE          0.528977
1003  41152404.pdf                     BPO          0.498680
1666  37242217.pdf  INFORMATION-TECHNOLOGY          0.490032
1232  10562768.pdf                 APPAREL          0.483915
909   12011623.pdf             ENGINEERING          0.478226

In [38]:
for i, row in results.iterrows():

    print("=" * 80)

    print("Filename:", row["filename"])
    print("Category:", row["label"])
    print("Similarity:", round(row["similarity_score"], 4))

    print("\nResume preview:")
    print(row["text"][:1000])

================================================================================
Filename: 18448085.pdf
Category: AUTOMOBILE
Similarity: 0.529

Resume preview:
DATA ANALYST
Professional Summary
Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Green Belt with strong background in
statistics, mathematics and logical problem solving looking for a dynamic opportunity in data driven fields of analytics and statistical modeling.
Core Qualifications
Data Science Tools: R, Base SAS, Python (Numpy, Pandas, Matplotlib, Scikit- learn), SPSS, Minitab, MATLAB, Apache Spark, SQL, MS
Excel, MS Visio, Tableau MySQL, Oracle Database, Microsoft Access Key Competencies: Data Extraction, Data Wrangling, Data Analysis,
Data Visualization, Regression Analysis (Linear, Logistic and Multinomial), Time Series Analysis, Association Rule Mining, Monte Carlo
Simulation, Optimization, Random Forests
Experience
07/2016 to Current
Data Analyst Company Name ï¼​ State
09/2015 to 05/2016
Student Manager Company Name ï¼​ State
Undertook a leadership and advisory role in training newcomers to hone their culinary and behavioral skil
================================================================================
Filename: 41152404.pdf
Category: BPO
Similarity: 0.4987

Resume preview:
TEST ANALYST-INTERN/CONTRACTOR
Profile
3+ years of professional experience in Software Testing. Experience in working with Agile Software Development. Strong scripting skills with
good expereince in test automation. Expertise in Manual and Automation testing of various web and mobile- based applications. Good
programming skills accompanied by excellent analytical and problem solving skills. Hands on experience in preparing Test Plans, Test Cases,
Automated Tests and executing the same. Proven experience in testing GIS applications. Experience in working with E-commerce, Banking and
Insurance domains. Experience in User Acceptance Testing, System Integration Testing, Performance Testing, Decision Table Testing and
Regression Testing. Good experience with developing and maintaining the test documentation. Self motivated with strong passion for delivering
quality software. Strong Project Management skills with flexibility and willingness to work on a variety of projects while demonstratin
================================================================================
Filename: 37242217.pdf
Category: INFORMATION-TECHNOLOGY
Similarity: 0.49

Resume preview:
INFORMATION TECHNOLOGY CONSULTANT
Career Overview
Accomplished information technology professional with over 18 years of diverse technology, process analysis, project management, and
information management experience. Proven ability to successfully implement technology solutions, stay within time and budget constraints, and
improve efficiency through proper risk management, task coordination, and resource utilization. Core Competencies Project Management Systems
/ Network Reporting Proposal Development Web Design & Development SOP & Policy Writing Systems & Process Consulting Document
Management Technically-advanced information technology specialist successful in software administration and data communications.Experienced
Computer Systems Analyst with diverse industry experience in banking, healthcare, insurance and government. Professional expertise includes
systems applications, disaster recovery planning and information protection analysis.
Qualifications
Microsoft Windows (7, 8, 20
================================================================================
Filename: 10562768.pdf
Category: APPAREL
Similarity: 0.4839

Resume preview:
ASSISTANT BANKING CENTER MANAGER I
Summary
Experienced in Signals analysis, Geo-Spatial analysis, Electronic Warfare analysis, Networks and Threat analysis, and DNR. Limited knowledge
of performing DNI analysis. Basic knowledge of computer network applications from the World Wide Web, printers, email, and instant
messaging. Knowledge in Local Area Networks as well as Wide Area Networks. Expert working knowledge and experience with Google Earth,
Microsoft Office Suite, various SIGINT Geospatial Analyst/Signal Analysis/SIGDEV collection, identification and analysis processing tools,
applications, and databases. Experienced in analytic research and development techniques along with management of analysis databases, and
products. Excellent oral and written communication skills, regular displays of high levels of professionalism and problem-solving skills. Bloomberg
certified as of 2014. Highly adaptive to changing environments, a self-starter and people motivator with a broad set of analyt
================================================================================
Filename: 12011623.pdf
Category: ENGINEERING
Similarity: 0.4782

Resume preview:
ENGINEERING AND QUALITY TECHNICIAN
Career Overview
A highly experienced skilled graduate with Analytics degree with a very good experience in SAS, Web scraping, SQL, Predictive modelling and
data visualization. Excellent ability in identifying data requirements for analysis, data cleaning, munging and model building; Ensures the organization
uses it effectively to reach profit and growth objectives. Comfortable with data handling, modeling, and coding, and have an appreciation of what
makes sense from a business standpoint. More than six years of experience working as a researcher, data analyst, and environmental science and
Technology Instructor. Experience in SQL, data warehousing, maintaining, securing and stabilizing data layers and testing to identify data and
product defects introduced in the system. Customer segmentation, product positioning and mapping and conjoint analysis Modelling: Design and
implement statistical / predictive models and cutting edge algorithms utilizing div

In [39]:
test_queries = {
    "Machine Learning": """
    Python, machine learning, data analysis, predictive modeling,
    statistics, deep learning and data science
    """,

    "Human Resources": """
    Human resources, recruitment, employee relations, onboarding,
    HR administration, payroll and personnel management
    """,

    "Finance": """
    Financial analysis, accounting, auditing, budgeting,
    financial reporting, Excel and financial management
    """,

    "Software / IT": """
    Software development, Python, Java, programming,
    databases, web development and technical systems
    """
}

In [40]:
all_search_results = {}

for query_name, query_text in test_queries.items():

    print("\n" + "=" * 100)
    print("QUERY:", query_name)
    print("=" * 100)

    results = search_resumes(
        query_text,
        top_k=5
    )

    all_search_results[query_name] = results

    print(
        results[
            ["filename", "label", "similarity_score"]
        ].to_string(index=False)
    )

====================================================================================================
QUERY: Machine Learning
====================================================================================================
    filename                  label  similarity_score
18448085.pdf             AUTOMOBILE          0.425257
12011623.pdf            ENGINEERING          0.394623
22946204.pdf             AUTOMOBILE          0.391666
62994611.pdf            AGRICULTURE          0.376799
20674668.pdf INFORMATION-TECHNOLOGY          0.369640

====================================================================================================
QUERY: Human Resources
====================================================================================================
    filename   label  similarity_score
32947778.pdf      HR          0.670653
87968870.pdf      HR          0.663948
23011221.pdf FITNESS          0.662030
14225422.pdf      HR          0.658777
17812897.pdf      HR          0.657158

====================================================================================================
QUERY: Finance
====================================================================================================
    filename      label  similarity_score
24833063.pdf    FINANCE          0.638607
12802330.pdf ACCOUNTANT          0.600305
31948488.pdf    FINANCE          0.595494
27637576.pdf ACCOUNTANT          0.592054
81677620.pdf    FINANCE          0.589590

====================================================================================================
QUERY: Software / IT
====================================================================================================
    filename                  label  similarity_score
62994611.pdf            AGRICULTURE          0.557208
12144825.pdf               AVIATION          0.512867
20674668.pdf INFORMATION-TECHNOLOGY          0.506041
12415691.pdf               DESIGNER          0.498391
22946204.pdf             AUTOMOBILE          0.480804

In [41]:
for query_name, results in all_search_results.items():

    print("\n\n" + "#" * 100)
    print("QUERY:", query_name)
    print("#" * 100)

    for rank, (_, row) in enumerate(
        results.head(3).iterrows(),
        start=1
    ):

        print("\n" + "-" * 80)
        print(f"RANK {rank}")
        print("Filename:", row["filename"])
        print("Category:", row["label"])
        print("Similarity:", round(row["similarity_score"], 4))

        print("\nResume Preview:")
        print(row["text"][:1200])

####################################################################################################
QUERY: Machine Learning
####################################################################################################

--------------------------------------------------------------------------------
RANK 1
Filename: 18448085.pdf
Category: AUTOMOBILE
Similarity: 0.4253

Resume Preview:
DATA ANALYST
Professional Summary
Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Green Belt with strong background in
statistics, mathematics and logical problem solving looking for a dynamic opportunity in data driven fields of analytics and statistical modeling.
Core Qualifications
Data Science Tools: R, Base SAS, Python (Numpy, Pandas, Matplotlib, Scikit- learn), SPSS, Minitab, MATLAB, Apache Spark, SQL, MS
Excel, MS Visio, Tableau MySQL, Oracle Database, Microsoft Access Key Competencies: Data Extraction, Data Wrangling, Data Analysis,
Data Visualization, Regression Analysis (Linear, Logistic and Multinomial), Time Series Analysis, Association Rule Mining, Monte Carlo
Simulation, Optimization, Random Forests
Experience
07/2016 to Current
Data Analyst Company Name ï¼​ State
09/2015 to 05/2016
Student Manager Company Name ï¼​ State
Undertook a leadership and advisory role in training newcomers to hone their culinary and behavioral skills.
PROJECTS Classification of Customers for Credit Card Company Jan 2016 Â​ May 2016 Performed a logistic regression on a credit card
company dataset to classify clients as credible and non-credible.

--------------------------------------------------------------------------------
RANK 2
Filename: 12011623.pdf
Category: ENGINEERING
Similarity: 0.3946

Resume Preview:
ENGINEERING AND QUALITY TECHNICIAN
Career Overview
A highly experienced skilled graduate with Analytics degree with a very good experience in SAS, Web scraping, SQL, Predictive modelling and
data visualization. Excellent ability in identifying data requirements for analysis, data cleaning, munging and model building; Ensures the organization
uses it effectively to reach profit and growth objectives. Comfortable with data handling, modeling, and coding, and have an appreciation of what
makes sense from a business standpoint. More than six years of experience working as a researcher, data analyst, and environmental science and
Technology Instructor. Experience in SQL, data warehousing, maintaining, securing and stabilizing data layers and testing to identify data and
product defects introduced in the system. Customer segmentation, product positioning and mapping and conjoint analysis Modelling: Design and
implement statistical / predictive models and cutting edge algorithms utilizing diverse sources of data to predict Diversified experience with
Engineering, Manufacturing, Retailing, Higher Education and IT /Data related companies Fascinated by learning cutting edge technologies, suc

--------------------------------------------------------------------------------
RANK 3
Filename: 22946204.pdf
Category: AUTOMOBILE
Similarity: 0.3917

Resume Preview:
Highlights
Prog. Languages: C (5+ yrs), Python (3+ yrs), Java (3+ yrs), MATLAB (Simulink) (5+ yrs), R (2 yrs), Processing (2yrs), SQL(4+ yrs),
PLC(2 yrs)
Doc. Editing: Word/PPT/Excel, Pages/Numbers/Keynote, LATEX
Mechanical Design: AutoCAD (6 yrs), Solidworks (5+ yrs)
Mechanical Skills: MakerBot 3D print, Laser cut, Mill, Drill, Lathe Machine.
Statistics Softwares: STATA, SPSS
Database Softwares: SQL Server (4 yrs), Navicat (2 yrs)
Operating Systems: Windows 7/10, OS X
Experience
Company Name June 2016 to Current R&D Product Development Engineer
City
Design and build a tail-sitter VTOL(vertical take off and landing) UAV(unmanned aerial vehicle) which.
takes off and lands vertically and travels horizontally.
Main duties include but not limit to aerodynamics.
modeling, UAV control system design, mechanical manufacturing, simulation and tuning/experiments.
Company Name May 2015 to February 2016 Research assistant
City
Research assistant for Wharton School environment economics projects on Europe Emission Trading.
System (EU ETC).
Main duties include large scale data collecting, cleaning, merging, database.
construction and data analysis, etc.
Completed with skills ranging from Java,


####################################################################################################
QUERY: Human Resources
####################################################################################################

--------------------------------------------------------------------------------
RANK 1
Filename: 32947778.pdf
Category: HR
Similarity: 0.6707

Resume Preview:
HR MANAGER
Summary
Human Resources Professional with practical understanding of business needs. Areas of expertise include conflict management and employee
training. Highly effective at incorporating creative leadership skills to achieve business objectives. Directs projects that improve efficiency while
meeting deadlines and budget requirements.
Highlights
Hiring and retention
Training and development
Recruiting
Compensation/payroll
Employee relations
Personnel records maintenance
New hire orientation
Meeting planning
Workers' compensation knowledge
Labor relations
MS Office
Excellent interpersonal and coaching skills
HRIS technologies
Staff training and development
Human resources audits
HR policies and procedures expertise
Project management
Human resource laws knowledge
Appointment setting
Database management
Experience
Company Name City , State HR Manager 01/2012 to 04/2015
Planned, directed, and coordinated human resource management activities to maximize the strategic use of human resources and maintained
functions such as workers compensation, recruitment, personnel policies, and regulatory compliance.
Key Results: New Hire Orientation, on-boarding activities and other HR f

--------------------------------------------------------------------------------
RANK 2
Filename: 87968870.pdf
Category: HR
Similarity: 0.6639

Resume Preview:
HR GENERALIST
Summary
Energetic, Bilingual Human Resources Professional offeringÂ ~11 years of extensive and successful experience administering various HR plans and
procedures. Emphasis on recruitment/retention, management and HR principles & practices. Expertise in employee relations and organization
development through education, and experience, seeks a similar role to produce immediate growth contribution to a rewarding company.
Highlights
Hiring and retention
Training and development
Compensation and benefits
New hire orientation
Compensation administration/payroll
Mediation expertise
Employee relations
Labor agreements
Regulatory compliance
Knowledgeable in all HR Systems
Experience
Company Name City , State HR Generalist 12/2014 to Current
Develops Human Resources policies, procedures, plans and budgets.
The safety of the workforce for recruitment, development and compensation of a superior workforce.
Develops an employee-oriented culture that emphasizes quality, continuous improvement and high performance.
Conduct new employee orientation to foster positive attitude toward organizational objectives.
Serve as a link between management and employees by handling questions, int

--------------------------------------------------------------------------------
RANK 3
Filename: 23011221.pdf
Category: FITNESS
Similarity: 0.662

Resume Preview:
HUMAN RESOURCES MANAGER
www.linkedin.com/in/theealimuniz
Professional Summary
Dedicated Human Resource Manager with hands-on personnel management experience, and business-related academic knowledge that blends
seamlessly into a position such as Human Resources Manager. Adapt at addressing sensitive issues and maintaining the strictest of confidentiality.
Particularly organized and efficient with a flair for prioritizing. As well as highly skilled at incorporating creative leadership skills to achieve business
objectives.
Skills
Equal opportunities
facilitation
Recruitment strategies
Labor negotiations
Recordkeeping
Compensation
structuring
Benefits administration
Payroll coordination
Workforce
improvements
Company organization
Training programs
Human Resources
Certification
New employee
orientations
Compensation and
benefits
Termination procedures
MS Office proficient
Project management
FMLA comprehension
Society for Human
Resource Management
Team buildingÂ
In-depth knowledge of
HR Compliance
Trained in
FMLA/ADA/EEO/WC
Knowledgeable in all
HR Systems
Professionals in Human
Resources Association
Employee recruitment
Business mediation
ADP Workforce Now
SharePoint Intranet
softwar
S


####################################################################################################
QUERY: Finance
####################################################################################################

--------------------------------------------------------------------------------
RANK 1
Filename: 24833063.pdf
Category: FINANCE
Similarity: 0.6386

Resume Preview:
ACTING FINANCE MANAGER
Summary
Innovative Accountant proficient in extracting financial data from various reporting systems and suggesting key operational changes.
Accommodating [Job Title] who effectively manages strict deadlines, schedules and repetitive tasks with a positive, can-do attitude. An accountant
and analyst with more than 8-years, proven experience spanning over oil and gas services, manufacturing, and trading business. The experience is
not limited to Financial & Management reporting, IFRS and US GAAP, Working Capital management, Cost control and reduction measures,
Internal Controls, ERP system implementation and development(Oracle, Hyperion, and Quick Books), Statutory compliance, Payroll & inventory
management, Business insight and support decision making, Planning, budgeting, forecasting, Capex control, Leadership and team management,
dealing with banks, internal/external auditors & business lawyers, advising management on financial strategy, Commercial proposals and evaluation,
risks coverage, Negotiating contract, dealing with client, Setting up new KPIs/Standards and measuring performance, due diligence,
implementation of corporate policies and governance. Key

--------------------------------------------------------------------------------
RANK 2
Filename: 12802330.pdf
Category: ACCOUNTANT
Similarity: 0.6003

Resume Preview:
LEAD ACCOUNTANT
Highlights
QuickBooks, Peachtree, In-house Accounting Systems and Financial Reporting, MAS 90, FAR, WAWF, Great Plains, Integration
Manager, FRx reporting.
Hyperion Workspace, Planning, Enterprise, Essbase, Schedules and Reports, Crystal Reports, MS Office with strong Excel skill
Financial Accounting
Database Management
Budget Administration
Performance Reporting
Tax Preparation and Compliance
Forecasting/Trend Analysis
Strategic Planning
Cash-Flow Analysis
Variance Analysis
Sarbanes-Oxley Research and Compliance
Experience
Lead Accountant
November 2011 to Current Company Name ï¼​ City , State
Experience in various areas including, but not limited to: operating budgets, financial analysis/planning, financial statements and reporting,
accounting policies and procedure, cash flow, taxes, auditing, and business process improvements.
Manage various areas in financial accounting, budgeting and financial analysis.
Execute qualitative and quantitative analysis techniques to minimize risks and liabilities.
Develop and implement system processes to achieve financial discipline and improve the overall efficiency of the organization.
Provide strong analytical skills, good rel

--------------------------------------------------------------------------------
RANK 3
Filename: 31948488.pdf
Category: FINANCE
Similarity: 0.5955

Resume Preview:
FINANCE MANAGER
Summary
Highly organized and detail-focused Accounting Technician with an exceptional track record of accurately handling financial reporting in deadline-
oriented environments. Skilled in recording transactions, posting debits and credits, reconciling accounts, and ensuring accuracy and completeness
of data. Expertise in developing and delivering monthly, quarterly, and annual financial statements within tight deadlines. Proficiency in managing
accounts payable and accounts receivable, generating invoices and monthly statements for clients. Proven ability to identify and implement
improvements to streamline processes and increase efficiency and productivity.
Highlights
Microsoft Word, Microsoft Excel, Financial Edge and QuickBooks and able to learn proprietary systems/applications quickly and easily.
Skill Proficiencies
Quarterly Reports
Accounts Payable/Receivable *Budget Preparation
Process Improvement *Financial Statements
Reconciliation
Experience
Finance Manager
November 2009 to October 2015 Company Name - City , State
Prepare schedules and consolidate information for annual budget planning.
Prepare financial statements with budget and actual comparisons usin


####################################################################################################
QUERY: Software / IT
####################################################################################################

--------------------------------------------------------------------------------
RANK 1
Filename: 62994611.pdf
Category: AGRICULTURE
Similarity: 0.5572

Resume Preview:
SOFTWARE DEVELOPER
Professional Summary
Enthusiastic computer engineer eager to contribute to team success through hard work, attention to detail and excellent organizational skills.
Technical professional with complete understanding of entire software development life cycle. Respectful self-motivator gifted at finding reliable
solutions for software issues. Experienced in c#, python, HTML, SQL, node.js/javascript and working knowledge of Restful API design &
implementations. Fluent in English and Turkish and accustomed to working with cross-cultural, global teams.
Skills
C#, HTML, CSS, JavaScript, 5 years of experience
SQL, 5 years of experience
Python, MatLab, MongoDB, Tableau, Node JS
Frameworks: .Net, Devexpress, TensorFlow, Keras, Scikit-learn, Pandas, NLTK.
Search Engine Optimization
Net
API
CSS
Clients
Database development
Designing
English
HTML
Image processing
JavaScript
Leadership
Marketing
MatLab
C#
Office
Windows
Project management
Speaker
Python
Sales
Search Engine Optimization
Spanish
SQL
System architecture
Turkish
User Interface
Web site
Written
Work History
Software Developer , 12/2015 to Current
Company Name â€“ City , State
Project was tasked to design an Inter

--------------------------------------------------------------------------------
RANK 2
Filename: 12144825.pdf
Category: AVIATION
Similarity: 0.5129

Resume Preview:
SOFTWARE ENGINEERING CO-OP
Summary
Highly skilled and Accomplished computer software specialist with more than 7+ years of technical experience in programming development
across multiple platforms, software design, development and integration. Advanced knowledge of MySQL, CSS, C++ with expertise in all aspects
of the software development life cycle, including requirements analysis, design, development and production support. Experienced Software
Developer dedicated to constantly improving tools and infrastructure to maximize productivity, minimize system downtime and quickly respond to
the changing needs of the business which does not exclude an intensive background in develop, testing, and debugging code, designing interfaces,
and administrating systems and networks. Tenacious hard worker, self-directed and motivated, great leadership skills, able to work as a team, and
adaptable to a quick changing technical environment.
Highlights
MySQL, PostgreSQL, SQLite, NoSQL, LevelDB
Programming Languages: C, C++, Perl, PHP, Python, Go, JavaScript, Bash, SQL, Visual Basic, .NET
Other Languages: CSS, HTML, XML, Markdown, Regular expression, SASS
Operating Systems: Linux, Unix
Tools: Netbeans

--------------------------------------------------------------------------------
RANK 3
Filename: 20674668.pdf
Category: INFORMATION-TECHNOLOGY
Similarity: 0.506

Resume Preview:
INFORMATION TECHNOLOGY SPECIALIST III (DRUPAL DEV)
Summary
Drupal developer with five years of experience in site building, and frontend and backend development. Skills in theming, as well. Driven to
provide excellent service and high-quality coding to create secure and functional sites for clients. Expert in Drupal and up to date on the latest
developments and versions. Managed several projects for the NYSED Redesign Project using both Drupal 7 and Drupal 8, including full Drupal
deployment services. Earned the respect and the trust from both the NYSED ITS and Program Office Managements.
Core Qualifications
â€¢ Superior proficiency in high-level Drupal 7 and Drupal 8 Development
â€¢ Excellent proficiency in using Drupal Ajax and jQuery in web development
â€¢ Exceptional knowledge of Drupal prior versions and upgrades
â€¢ Extensive expertise with versioning management systems
â€¢ Strong ability to manage multiple concurrent projects
â€¢ High problem solving and analytical skills
Technical Skills
Programming and Scripting Languages: C++, Java, JavaScript, PHP, Python, AJAX
Data-Oriented Languages and Databases: SQL, PL/SQL, Oracle Database, DMS II, PL/SQL, JDBC
Markup and Stylesheet

In [42]:
evaluation_records = []

for query_name, results in all_search_results.items():

    for rank, (_, row) in enumerate(
        results.iterrows(),
        start=1
    ):

        evaluation_records.append({
            "query": query_name,
            "rank": rank,
            "filename": row["filename"],
            "label": row["label"],
            "similarity_score": row["similarity_score"]
        })

evaluation_df = pd.DataFrame(evaluation_records)

evaluation_df

,query,rank,filename,label,similarity_score
0,Machine Learning,1,18448085.pdf,AUTOMOBILE,0.425257
1,Machine Learning,2,12011623.pdf,ENGINEERING,0.394623
2,Machine Learning,3,22946204.pdf,AUTOMOBILE,0.391666
3,Machine Learning,4,62994611.pdf,AGRICULTURE,0.376799
4,Machine Learning,5,20674668.pdf,INFORMATION-TECHNOLOGY,0.369640
5,Human Resources,1,32947778.pdf,HR,0.670653
6,Human Resources,2,87968870.pdf,HR,0.663948
7,Human Resources,3,23011221.pdf,FITNESS,0.662030
8,Human Resources,4,14225422.pdf,HR,0.658777
9,Human Resources,5,17812897.pdf,HR,0.657158
10,Finance,1,24833063.pdf,FINANCE,0.638607
11,Finance,2,12802330.pdf,ACCOUNTANT,0.600305
12,Finance,3,31948488.pdf,FINANCE,0.595494
13,Finance,4,27637576.pdf,ACCOUNTANT,0.592054
14,Finance,5,81677620.pdf,FINANCE,0.589590
15,Software / IT,1,62994611.pdf,AGRICULTURE,0.557208
16,Software / IT,2,12144825.pdf,AVIATION,0.512867
17,Software / IT,3,20674668.pdf,INFORMATION-TECHNOLOGY,0.506041
18,Software / IT,4,12415691.pdf,DESIGNER,0.498391
19,Software / IT,5,22946204.pdf,AUTOMOBILE,0.480804

In [43]:
evaluation_df["relevant"] = None

evaluation_df.head()

,query,rank,filename,label,similarity_score,relevant
0,Machine Learning,1,18448085.pdf,AUTOMOBILE,0.425257,None
1,Machine Learning,2,12011623.pdf,ENGINEERING,0.394623,None
2,Machine Learning,3,22946204.pdf,AUTOMOBILE,0.391666,None
3,Machine Learning,4,62994611.pdf,AGRICULTURE,0.376799,None
4,Machine Learning,5,20674668.pdf,INFORMATION-TECHNOLOGY,0.369640,None

In [44]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 2.1 MB/s eta 0:00:00

In [45]:
from groq import Groq

In [ ]:
# API key is loaded securely using an environment variable.
# Set GROQ_API_KEY before running the LLM section.

In [47]:
client = Groq(
    api_key=os.environ.get("GROQ_API_KEY")
)

In [48]:
completion = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {
            "role": "user",
            "content": "Say hello and confirm that you are working."
        }
    ]
)

print(completion.choices[0].message.content)

Hello. I'm functioning as intended and I'm here to assist you with any questions or topics you'd like to discuss.

In [49]:
def retrieve_context(query, top_k=3):

    results = search_resumes(query, top_k=top_k)

    context = ""

    for rank, (_, row) in enumerate(results.iterrows(), start=1):

        context += f"""

RESUME {rank}
Filename: {row['filename']}
Category: {row['label']}

{row['text'][:2500]}

----------------------------
"""

    return context, results

In [50]:
query = """
Find candidates with experience in Python, machine learning,
data analysis and predictive modeling.
"""

context, retrieved_results = retrieve_context(
    query,
    top_k=3
)

print(
    retrieved_results[
        ["filename", "label", "similarity_score"]
    ]
)

print("\nCONTEXT PREVIEW:\n")
print(context[:3000])

          filename        label  similarity_score
2121  18448085.pdf   AUTOMOBILE          0.517544
909   12011623.pdf  ENGINEERING          0.493517
2077  62994611.pdf  AGRICULTURE          0.490451

CONTEXT PREVIEW:



RESUME 1
Filename: 18448085.pdf
Category: AUTOMOBILE

DATA ANALYST
Professional Summary
Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Green Belt with strong background in
statistics, mathematics and logical problem solving looking for a dynamic opportunity in data driven fields of analytics and statistical modeling.
Core Qualifications
Data Science Tools: R, Base SAS, Python (Numpy, Pandas, Matplotlib, Scikit- learn), SPSS, Minitab, MATLAB, Apache Spark, SQL, MS
Excel, MS Visio, Tableau MySQL, Oracle Database, Microsoft Access Key Competencies: Data Extraction, Data Wrangling, Data Analysis,
Data Visualization, Regression Analysis (Linear, Logistic and Multinomial), Time Series Analysis, Association Rule Mining, Monte Carlo
Simulation, Optimization, Random Forests
Experience
07/2016 to Current
Data Analyst Company Name ï¼​ State
09/2015 to 05/2016
Student Manager Company Name ï¼​ State
Undertook a leadership and advisory role in training newcomers to hone their culinary and behavioral skills.
PROJECTS Classification of Customers for Credit Card Company Jan 2016 Â​ May 2016 Performed a logistic regression on a credit card
company dataset to classify clients as credible and non-credible.
Extracted crucial factors to simplify the classification model using exploratory factor analysis.
Developed and validated a model to classify the future customers and aid decision-making.
Simulation Analysis of Adding a Second Parking Ticket Booth at a Mall Aug 2015 Â​ Dec 2015 Assessed distribution and trends of
incoming customer patterns performing statistical analysis on MATLAB and ExpertFit.
Additional booth modeled using Arena reduced average waiting time per customer from 6.2 minutes to 1.8 minutes.
Statistical Analysis of Defects in Clutch Plate Manufacturing - A Six Sigma Study Jan 2015 Â​ May 2015 The DMAIC methodology
(Define, Measure, Analyze, Improve and Control) was implemented to understand the cause of the defects and data was statistically
analyzed with the help of control charts using Minitab.
06/2013 to 07/2013
Intern Company Name
Identified the areas in the assembly line of a light commercial vehicle where more operations could be housed.
Developed a detailed model of improved layout to accommodate more operations using AutoCAD to improve the space utilization by
300%.
consultant
a self-storage company to classify the customers as 'worthy' and 'not worthy' based on their activity on the company website using the
Random Forest algorithm.
Built the model in R an

----------------------------


RESUME 2
Filename: 12011623.pdf
Category: ENGINEERING

ENGINEERING AND QUALITY TECHNICIAN
Career Overview
A highly experienced skilled graduate with Analytics degree with a very good experience in SAS, Web scraping, SQL, Predictive modelling and
data visualization. Excellent ability in identifying data requirements for analysis, data cleaning, munging and model building; Ensures the organizat

In [51]:
def ask_resume_rag(question, top_k=3):

    context, results = retrieve_context(
        question,
        top_k=top_k
    )

    messages = [
        {
            "role": "system",
            "content": """
You are a recruitment assistant analyzing retrieved resumes.

Answer the user's question ONLY using the information in the
provided resume context.

Compare candidates when the question asks which candidate is
strongest or most suitable.

Use evidence from the resumes, such as skills, tools, projects,
experience, and qualifications, to make a reasoned comparison.

Do not say that you cannot determine the answer if the resume
context contains enough evidence to make a reasonable comparison.
If evidence is limited, state that clearly but still provide the
best-supported conclusion.
"""
        },
        {
            "role": "user",
            "content": f"""
RESUME CONTEXT:

{context}

QUESTION:
{question}
"""
        }
    ]

    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=messages,
        temperature=0.2
    )

    answer = completion.choices[0].message.content

    return answer, results

In [52]:
question = """
Which candidate appears to have the strongest experience in
machine learning and predictive modeling? Explain why.
"""

answer, rag_results = ask_resume_rag(
    question,
    top_k=3
)

print(answer)

Based on the provided resume context, Resume 3 (PHD CANDIDATE IN FINANCE) appears to have the strongest experience in machine learning and predictive modeling.

The candidate has listed proficiency in R, SAS, SQL, C++, Fortran, and VBA, which are programming languages commonly used in machine learning and predictive modeling. Additionally, they have highlighted advanced modeling skills, project management experience, critical thinking skills, complex problem-solving skills, and superior research skills.

Their research experience, as a PhD candidate in finance, includes conducting research in finance, specifically asset pricing and econometric modeling, using advanced statistical techniques such as Maximum Entropy Econometrics and GARCH Process. They have also worked on projects related to market sentiment and its effects on stock returns, which involves predictive modeling.

While Resume 2 (VP, PRINCIPAL) has experience in designing, developing, and implementing mission-critical systems, their focus is more on data modeling, data management, and data governance, rather than machine learning and predictive modeling specifically.

Resume 1 (BANKING) does not have any relevant experience in machine learning or predictive modeling.

Therefore, based on the provided resume context, Resume 3 appears to have the strongest experience in machine learning and predictive modeling.

In [53]:
question = """
Which retrieved candidate has the strongest technical and programming
skill set? Compare the candidates and explain your reasoning.
"""

answer, rag_results = ask_resume_rag(question, top_k=3)

print(answer)

Based on the provided resume context, I would conclude that Resume 2 (Information Designer) has the strongest technical and programming skill set.

Here's a comparison of the candidates:

- Resume 1 (IT Consultant) has a broad range of technical skills, including proficiency in Microsoft Office, various IT management tools, and experience with Windows, Linux, and Unix operating systems. However, the skills listed are more focused on IT management and administration rather than programming.

- Resume 2 (Information Designer) lists a wide range of programming languages, including C, C++, C#.NET, Java, Python, PHP, and Mathematica. The candidate also has experience with various software development tools, such as TOAD for Oracle, SQL Developer, Visual Studio, and Eclipse. Additionally, the candidate has experience with Unix/Linux System Administration, Oracle Database Administration, and MySQL database administration.

- Resume 3 (Information Technology Consultant) lists a broad range of technical skills, including proficiency in various programming languages, such as Java, JavaScript, and C++. However, the skills listed are more focused on general IT consulting and project management rather than specialized programming skills.

Based on the resume context, Resume 2 (Information Designer) has the strongest technical and programming skill set due to the extensive list of programming languages and software development tools listed.

In [54]:
question = """
Summarize the key skills and experience of the most relevant
candidate for machine learning and data analysis.
"""

answer, rag_results = ask_resume_rag(question, top_k=3)

print(answer)

Based on the provided resume context, the most relevant candidate for machine learning and data analysis is Resume 1 (Engineering and Quality Technician) and Resume 2 (Data Analyst).

However, Resume 1 has more extensive experience in machine learning and data analysis, with skills in:

* Predictive modeling
* Data visualization
* SQL
* Web scraping
* R, SAS, and Python programming
* Experience in handling large datasets and data warehousing
* Familiarity with various machine learning algorithms, including Random Forests, Decision Trees, and Boosted Trees

Resume 2 also has strong skills in machine learning and data analysis, with experience in:

* Data Science Tools: R, Base SAS, Python (Numpy, Pandas, Matplotlib, Scikit-learn), SPSS, Minitab, MATLAB, Apache Spark, SQL, MS Excel, MS Visio, Tableau MySQL, Oracle Database, Microsoft Access
* Key Competencies: Data Extraction, Data Wrangling, Data Analysis, Data Visualization, Regression Analysis (Linear, Logistic and Multinomial), Time Series Analysis, Association Rule Mining, Monte Carlo Simulation, Optimization, Random Forests

However, Resume 1 has more experience in applying machine learning and data analysis to real-world problems, with projects such as:

* Developing predictive models for semiconductor production process development
* Conducting data analysis for environmental science and technology
* Managing a team of 4 and evaluating the performance of students

Therefore, Resume 1 is the most relevant candidate for machine learning and data analysis.

In [55]:
question = """
What machine learning, statistical modeling, and data analysis
techniques are mentioned across the retrieved resumes?
"""

answer, rag_results = ask_resume_rag(question, top_k=3)

print(answer)

Based on the provided resumes, the following machine learning, statistical modeling, and data analysis techniques are mentioned:

1. **Machine Learning:**
	* Random Forests (RESUME 2, RESUME 3)
	* Decision Trees (RESUME 2)
	* Boosted Trees (RESUME 2)
	* Ridge, LASSO, and Elastic Net regression models (RESUME 2)
	* Logistic Regression (RESUME 2, RESUME 3)
	* Monte Carlo Simulation (RESUME 3)
2. **Statistical Modeling:**
	* Predictive modeling (RESUME 1)
	* Data visualization (RESUME 1, RESUME 2, RESUME 3)
	* Statistical analysis (RESUME 2, RESUME 3)
	* Regression Analysis (Linear, Logistic, and Multinomial) (RESUME 3)
	* Time Series Analysis (RESUME 3)
	* Association Rule Mining (RESUME 3)
3. **Data Analysis:**
	* Data extraction (RESUME 3)
	* Data wrangling (RESUME 3)
	* Data analysis (RESUME 2, RESUME 3)
	* Outlier analysis (RESUME 2)
	* Dimension Reduction using PCA (RESUME 2)
	* Clustering techniques (RESUME 2)
	* Conjoint analysis (RESUME 2)
	* Exploratory factor analysis (RESUME 3)
	* Control charts (RESUME 3)
	* Data mining (RESUME 2)

These techniques are mentioned across the three resumes, indicating that the candidates have experience and knowledge in various aspects of machine learning, statistical modeling, and data analysis.

In [59]:
evaluation_df["relevant"] = 0
evaluation_df

,query,rank,filename,label,similarity_score,relevant
0,Machine Learning,1,18448085.pdf,AUTOMOBILE,0.425257,0
1,Machine Learning,2,12011623.pdf,ENGINEERING,0.394623,0
2,Machine Learning,3,22946204.pdf,AUTOMOBILE,0.391666,0
3,Machine Learning,4,62994611.pdf,AGRICULTURE,0.376799,0
4,Machine Learning,5,20674668.pdf,INFORMATION-TECHNOLOGY,0.369640,0
5,Human Resources,1,32947778.pdf,HR,0.670653,0
6,Human Resources,2,87968870.pdf,HR,0.663948,0
7,Human Resources,3,23011221.pdf,FITNESS,0.662030,0
8,Human Resources,4,14225422.pdf,HR,0.658777,0
9,Human Resources,5,17812897.pdf,HR,0.657158,0
10,Finance,1,24833063.pdf,FINANCE,0.638607,0
11,Finance,2,12802330.pdf,ACCOUNTANT,0.600305,0
12,Finance,3,31948488.pdf,FINANCE,0.595494,0
13,Finance,4,27637576.pdf,ACCOUNTANT,0.592054,0
14,Finance,5,81677620.pdf,FINANCE,0.589590,0
15,Software / IT,1,62994611.pdf,AGRICULTURE,0.557208,0
16,Software / IT,2,12144825.pdf,AVIATION,0.512867,0
17,Software / IT,3,20674668.pdf,INFORMATION-TECHNOLOGY,0.506041,0
18,Software / IT,4,12415691.pdf,DESIGNER,0.498391,0
19,Software / IT,5,22946204.pdf,AUTOMOBILE,0.480804,0

In [60]:
evaluation_df.loc[
    evaluation_df["query"] == "Machine Learning",
    "relevant"
] = [1, 1, 1, 1, 0]

evaluation_df.loc[
    evaluation_df["query"] == "Human Resources",
    "relevant"
] = [1, 1, 1, 1, 1]


evaluation_df.loc[
    evaluation_df["query"] == "Finance",
    "relevant"
] = [1, 1, 1, 1, 1]


evaluation_df.loc[
    evaluation_df["query"] == "Software / IT",
    "relevant"
] = [1, 1, 1, 1, 1]

In [61]:
evaluation_df[
    ["query", "rank", "filename", "relevant"]
]

               query  rank      filename  relevant
0   Machine Learning     1  18448085.pdf         1
1   Machine Learning     2  12011623.pdf         1
2   Machine Learning     3  22946204.pdf         1
3   Machine Learning     4  62994611.pdf         1
4   Machine Learning     5  20674668.pdf         0
5    Human Resources     1  32947778.pdf         1
6    Human Resources     2  87968870.pdf         1
7    Human Resources     3  23011221.pdf         1
8    Human Resources     4  14225422.pdf         1
9    Human Resources     5  17812897.pdf         1
10           Finance     1  24833063.pdf         1
11           Finance     2  12802330.pdf         1
12           Finance     3  31948488.pdf         1
13           Finance     4  27637576.pdf         1
14           Finance     5  81677620.pdf         1
15     Software / IT     1  62994611.pdf         1
16     Software / IT     2  12144825.pdf         1
17     Software / IT     3  20674668.pdf         1
18     Software / IT     4  12415691.pdf         1
19     Software / IT     5  22946204.pdf         1

In [62]:
precision_at_5 = (
    evaluation_df
    .groupby("query")["relevant"]
    .mean()
    .reset_index()
)

precision_at_5.columns = [
    "query",
    "Precision@5"
]

precision_at_5

              query  Precision@5
0           Finance          1.0
1   Human Resources          1.0
2  Machine Learning          0.8
3     Software / IT          1.0

In [63]:
mean_precision_at_5 = precision_at_5["Precision@5"].mean()

print(
    f"Mean Precision@5: {mean_precision_at_5:.3f}"
)

Mean Precision@5: 0.950

In [64]:
evaluation_df.to_csv(
    "retrieval_evaluation.csv",
    index=False
)

precision_at_5.to_csv(
    "precision_at_5_results.csv",
    index=False
)

print("Evaluation results saved!")

Evaluation results saved!

In [65]:
faiss.write_index(index, "resume_faiss.index")

df[["filename", "label", "text"]].to_pickle(
    "resume_metadata.pkl"
)

print("FAISS index and metadata saved successfully!")

FAISS index and metadata saved successfully!

In [66]:
from google.colab import files

files.download("resume_faiss.index")
files.download("resume_metadata.pkl")
files.download("retrieval_evaluation.csv")
files.download("precision_at_5_results.csv")